credit_risk:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: ''
      port: 5432
      dbname: credit_risk
      schema: public
      threads: 4
